version: "2"

services:
  natsx:
    image: 'nats:1.1.0'
    entrypoint: "/gnatsd -m 8222 -user foo -pass secret --logtime=false -DV"
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats-server
  api:
    build:
      context: "./nats-docker-api"
    links:
      - natsx
    environment:
      - "NATS_URI=nats://natsx:4222"
    depends_on:
      - natsx
    ports:
      - "8282:8080"
  worker:
    build:
      context: "./nats-docker-worker"
    links:
      - natsx
    environment:
      - "NATS_URI=nats://natsx:4222"
    depends_on:
      - natsx
    ports:
      - "8484:8181"

  worker2:
    build:
      context: "./nats-docker-worker-2"
    links:
      - natsx
    environment:
      - "NATS_URI=nats://natsx:4222"
    depends_on:
      - natsx
    ports:
      - "8686:8181"     